# Generated by Django 5.0.6 on 2024-07-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('EO', 'Esperantujo')], default='', max_length=2)),
                ('avatar_url', models.URLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.CharField(default='EEEEEEEEE', max_length=9)),
                ('current_player', models.CharField(choices=[('X', 'Player X'), ('O', 'Player O')], default='X', max_length=1)),
                ('status', models.CharField(choices=[('I', 'Ongoing'), ('X', 'X Won'), ('O', 'O Won'), ('D', 'Draw')], default='I', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('player_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.CharField(choices=[('X', 'Player X'), ('O', 'Player O')], max_length=1)),
                ('position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.game')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('game', 'position')},
            },
        ),
    ]
